const regionsWithProvinces = [
  {
    region: "AUTONOMOUS REGION IN MUSLIM MINDANAO (ARMM)",
    provinces: [
      {
        provinceName: "Basilan",
        cities: [
          "Akbar",
          "Al-Barka",
          "Hadji Mohammad Ajul",
          "Hadji Muhtamad",
          "Isabela",
          "Lamitan",
          "Lantawan",
          "Maluso",
          "Sumisip",
          "Tabuan-Lasa",
          "Tipo-Tipo",
          "Tuburan",
          "Ungkaya Pukan",
        ],
      },
      {
        provinceName: "Lanao del Sur",
        cities: [
          "Amai Manabilang",
          "Bacolod-Kalawi",
          "Balabagan",
          "Balindong",
          "Bayang",
          "Binidayan",
          "Buadiposo-Buntong",
          "Bubong",
          "Butig",
          "Calanogas",
          "Ditsaan-Ramain",
          "Ganassi, Lanao del Sur",
          "Kapai",
          "Kapatagan, Lanao del Sur",
          "Lumba-Bayabao",
          "Lumbaca-Unayan",
          "Lumbatan",
          "Lumbayanague",
          "Madalum",
          "Madamba",
          "Maguing",
          "Malabang",
          "Marantao",
          "Marogong",
          "Masiu",
          "Mulondo, Lanao del Sur",
          "Pagayawan",
          "Piagapo",
          "Picong, Lanao del Sur",
          "Poona Bayabao",
          "Pualas",
          "Saguiaran",
          "Sultan Dumalondong",
          "Tagoloan, Lanao del Sur",
          "Tamparan",
          "Taraka, Lanao del Sur",
          "Tubaran",
          "Tugaya",
          "Wao, Lanao del Sur",
        ],
      },
      {
        provinceName: "Maguindanao",
        cities: [
          "Ampatuan",
          "Barira",
          "Buldon",
          "Buluan",
          "Cotabato City",
          "Datu Abdullah Sangki",
          "Datu Anggal Midtimbang",
          "Datu Blah T. Sinsuat",
          "Datu Hoffer Ampatuan",
          "Datu Montawal",
          "Datu Odin Sinsuat",
          "Datu Paglas",
          "Datu Piang",
          "Datu Salibo",
          "Datu Saudi-Ampatuan",
          "Datu Unsay",
          "General Salipada K. Pendatun",
          "Guindulungan",
          "Kabuntalan",
          "Mamasapano",
          "Mangudadatu",
          "Matanog",
          "Northern Kabuntalan",
          "Pagalungan",
          "Paglat",
          "Pandag",
          "Parang",
          "Rajah Buayan",
          "Shariff Aguak",
          "Shariff Saydona Mustapha",
          "South Upi",
          "Sultan Kudarat",
          "Sultan Mastura",
          "Sultan sa Barongis",
          "Sultan Sumagka",
          "Talayan",
          "Upi",
        ],
      },
      {
        provinceName: "Sulu",
        cities: [
          "Banguingui",
          "Hadji Panglima Tahil",
          "Indanan",
          "Jolo",
          "Kalingalan Caluang",
          "Lugus",
          "Luuk",
          "Maimbung",
          "Omar",
          "Panamao",
          "Pandami",
          "Panglima Estino",
          "Pangutaran",
          "Parang",
          "Pata",
          "Patikul",
          "Siasi",
          "Talipao",
          "Tapul",
        ],
      },
      {
        provinceName: "Tawi-Tawi",
        cities: [
          "Bongao",
          "Languyan",
          "Mapun",
          "Panglima Sugala",
          "Sapa-Sapa",
          "Sibutu",
          "Simunul",
          "Sitangkai",
          "South Ubian",
          "Tandubas",
          "Turtle Islands",
        ],
      },
    ],
  },
  {
    region: "CORDILLERA ADMINISTRATIVE REGION (CAR)",
    provinces: [
      {
        provinceName: "Abra",
        cities: [
          "Bangued",
          "Boliney",
          "Bucay",
          "Bucloc",
          "Daguioman",
          "Danglas",
          "Dolores",
          "La Paz",
          "Lacub",
          "Lagangilang",
          "Lagayan",
          "Langiden",
          "Licuan-Baay (Licuan)",
          "Luba",
          "Malibcong",
          "Manabo",
          "Peñarrubia",
          "Pidigan",
          "Pilar",
          "Sallapadan",
          "San Isidro",
          "San Juan",
          "San Quintin",
          "Tayum",
          "Tineg",
          "Tubo",
          "Villaviciosa",
        ],
      },
      {
        provinceName: "Apayao",
        cities: [
          "Calanasan",
          "Conner",
          "Flora",
          "Kabugao",
          "Luna",
          "Pudtol",
          "Santa Marcela",
        ],
      },
      {
        provinceName: "Benguet",
        cities: [
          "Atok",
          "Bakun",
          "Bokod",
          "Buguias",
          "Itogon",
          "Kabayan",
          "Kapangan",
          "Kibungan",
          "La Trinidad",
          "Mankayan",
          "Sablan",
          "Tuba",
          "Tublay",
        ],
      },
      {
        provinceName: "Ifugao",
        cities: [
          "Balbalan",
          "Lubuagan",
          "Pasil",
          "Pinukpuk",
          "Rizal",
          "Tabuk",
          "Tanudan",
          "Tinglayan",
        ],
      },
      {
        provinceName: "Kalinga",
        cities: [
          "Balbalan",
          "Lubuagan",
          "Pasil",
          "Pinukpuk",
          "Rizal",
          "Tabuk",
          "Tanudan",
          "Tinglayan",
        ],
      },
      {
        provinceName: "Mountain Province",
        cities: [
          "Sadanga",
          "Natonin",
          "Paracelis",
          "Barlig",
          "Bontoc",
          "Besao",
          "Sagada",
          "Bauko",
          "Tadian",
          "Sabangan",
        ],
      },
    ],
  },
  {
    region: "NATIONAL CAPITAL REGION (NCR)",
    provinces: [
      {
        provinceName: "NCR, CITY OF MANILA, FIRST DISTRICT",
        cities: [
          "Tondo I / II",
          "Binondo",
          "Quiapo",
          "San Nicolas",
          "Santa Cruz",
          "Sampaloc",
          "San Miguel",
          "Ermita",
          "Intramuros",
          "Malate",
          "Pandacan",
          "Port Area",
          "Santa Ana",
        ],
      },
      {
        provinceName: "CITY OF MANILA",
        cities: [
          "Tondo I / II",
          "Binondo",
          "Quiapo",
          "San Nicolas",
          "Santa Cruz",
          "Sampaloc",
          "San Miguel",
          "Ermita",
          "Intramuros",
          "Malate",
          "Pandacan",
          "Port Area",
          "Santa Ana",
        ],
      },
      {
        provinceName: "NCR, SECOND DISTRICT",
        cities: [
          "City of Mandaluyong",
          "City of Marikina",
          "City of Pasig",
          "Quezon City",
          "City of San Juan",
        ],
      },
      {
        provinceName: "NCR, THIRD DISTRICT",
        cities: [
          "Caloocan City",
          "City of Malabon",
          "City of Navotas",
          "City of Valenzuela",
        ],
      },
      {
        provinceName: "NCR, FOURTH DISTRICT",
        cities: [
          "City of Las Piñas",
          "City of Makati",
          "City of Muntinlupa",
          "City of Parañaque",
          "Pasay City",
          "Pateros",
          "Taguig City",
        ],
      },
    ],
  },
  {
    region: "REGION I (ILOCOS REGION)",
    provinces: [
      {
        provinceName: "Ilocos Norte",
        cities: [
          "Adams, Ilocos Norte",
          "Bacarra",
          "Badoc",
          "Bangui, Ilocos Norte",
          "Banna, Ilocos Norte",
          "Burgos, Ilocos Norte",
          "Carasi",
          "Currimao",
          "Dingras",
          "Dumalneg",
          "Marcos, Ilocos Norte",
          "Nueva Era, Ilocos Norte",
          "Pagudpud",
          "Paoay",
          "Pasuquin",
          "Piddig",
          "Pinili",
          "San Nicolas, Ilocos Norte",
          "Sarrat",
          "Solsona, Ilocos Norte",
          "Vintar",
        ],
      },
      {
        provinceName: "Ilocos Sur",
        cities: [
          "Alilem",
          "Banayoyo",
          "Bantay",
          "Burgos",
          "Cabugao",
          "Candon",
          "Caoayan",
          "Cervantes",
          "Galimuyod",
          "Gregorio del Pilar",
          "Lidlidda",
          "Magsingal",
          "Nagbukel",
          "Narvacan",
          "Quirino",
          "Salcedo",
          "San Emilio",
          "San Esteban",
          "San Ildefonso",
          "San Juan",
          "San Vicente",
          "Santa",
          "Santa Catalina",
          "Santa Cruz",
          "Santa Lucia",
          "Santa Maria",
          "Santiago",
          "Santo Domingo",
          "Sigay",
          "Sinait",
          "Sugpon",
          "Suyo",
          "Tagudin",
          "Vigan",
        ],
      },
      {
        provinceName: "La Union",
        cities: [
          "Agoo",
          "Aringay",
          "Bacnotan",
          "Bagulin",
          "Balaoan",
          "Bangar",
          "Bauang",
          "Burgos",
          "Caba",
          "Luna",
          "Naguilian",
          "Pugo",
          "Rosario",
          "San Fernando",
          "San Gabriel",
          "San Juan",
          "Santo Tomas",
          "Santol",
          "Sudipen",
          "Tubao",
        ],
      },
      {
        provinceName: "Pangasinan",
        cities: [
          "Agno, Pangasinan",
          "Aguilar, Pangasinan",
          "Alcala, Pangasinan",
          "Anda, Pangasinan",
          "Asingan",
          "Balungao",
          "Bani, Pangasinan",
          "Basista",
          "Bautista, Pangasinan",
          "Bayambang",
          "Binalonan",
          "Binmaley",
          "Bolinao",
          "Bugallon",
          "Burgos, Pangasinan",
          "Calasiao",
          "Dasol",
          "Infanta, Pangasinan",
          "Labrador, Pangasinan",
          "Laoac",
          "Lingayen",
          "Mabini, Pangasinan",
          "Malasiqui",
          "Manaoag",
          "Mangaldan",
          "Mangatarem",
          "Mapandan",
          "Natividad, Pangasinan",
          "Pozorrubio",
          "Rosales, Pangasinan",
          "San Fabian, Pangasinan",
          "San Jacinto, Pangasinan",
          "San Manuel, Pangasinan",
          "San Nicolas, Pangasinan",
          "San Quintin, Pangasinan",
          "Santa Barbara, Pangasinan",
          "Santa Maria, Pangasinan",
          "Santo Tomas, Pangasinan",
          "Sison, Pangasinan",
          "Sual",
          "Tayug",
          "Umingan",
          "Urbiztondo",
          "Villasis",
        ],
      },
    ],
  },
  {
    region: "REGION II (CAGAYAN VALLEY)",
    provinces: [
      {
        provinceName: "Batanes",
        cities: ["Basco", "Itbayat", "Ivana", "Mahatao", "Sabtang", "Uyugan"],
      },
      {
        provinceName: "Cagayan",
        cities: [
          "Abulug",
          "Alcala, Cagayan",
          "Allacapan",
          "Amulung",
          "Aparri",
          "Baggao",
          "Ballesteros, Cagayan",
          "Buguey",
          "Calayan, Cagayan",
          "Camalaniugan",
          "Claveria, Cagayan",
          "Enrile, Cagayan",
          "Gattaran",
          "Gonzaga, Cagayan",
          "Iguig",
          "Lal-lo",
          "Lasam",
          "Pamplona, Cagayan",
          "Peñablanca",
          "Piat, Cagayan",
          "Rizal, Cagayan",
          "Sanchez-Mira",
          "Santa Ana, Cagayan",
          "Santa Praxedes, Cagayan",
          "Santa Teresita, Cagayan",
          "Santo Niño, Cagayan",
          "Solana, Cagayan",
          "Tuguegarao City",
          "Tuao",
        ],
      },
      {
        provinceName: "Isabela",
        cities: [
          "Alicia, Isabela",
          "Angadanan",
          "Aurora, Isabela",
          "Benito Soliven",
          "Burgos, Isabela",
          "Cabagan",
          "Cabatuan, Isabela",
          "Cordon, Isabela",
          "Delfin Albano",
          "Dinapigue",
          "Divilacan",
          "Echague",
          "Gamu",
          "Jones, Isabela",
          "Luna, Isabela",
          "Maconacon",
          "Mallig",
          "Naguilian, Isabela",
          "Palanan",
          "Quezon, Isabela",
          "Quirino, Isabela",
          "Ramon, Isabela",
          "Reina Mercedes, Isabela",
          "Roxas, Isabela",
          "San Agustin, Isabela",
          "San Guillermo",
          "San Isidro, Isabela",
          "San Manuel, Isabela",
          "San Mariano, Isabela",
          "San Mateo, Isabela",
          "San Pablo, Isabela",
          "Santa Maria, Isabela",
          "Santo Tomas, Isabela",
        ],
      },
      {
        provinceName: "Nueva Vizcaya",
        cities: [
          "Alfonso Castañeda",
          "Ambaguio",
          "Aritao",
          "Bagabag, Nueva Vizcaya",
          "Bambang, Nueva Vizcaya",
          "Bayombong",
          "Diadi",
          "Dupax del Norte",
          "Dupax del Sur",
          "Kasibu",
          "Kayapa",
          "Quezon, Nueva Vizcaya",
          "Santa Fe, Nueva Vizcaya",
          "Solano, Nueva Vizcaya",
          "Villaverde, Nueva Vizcaya",
        ],
      },
      {
        provinceName: "Quirino",
        cities: [
          "Aglipay",
          "Cabarroguis",
          "Diffun",
          "Maddela",
          "Nagtipunan",
          "Saguday",
        ],
      },
    ],
  },
  {
    region: "REGION III (CENTRAL LUZON)",
    provinces: [
      {
        provinceName: "Aurora",
        cities: [
          "Baler",
          "Casiguran",
          "Dilasag",
          "Dinalungan",
          "Dingalan",
          "Dipaculao",
          "Maria Aurora",
          "San Luis",
        ],
      },
      {
        provinceName: "Bataan",
        cities: [
          "Abucay",
          "Bagac",
          "Dinalupihan",
          "Hermosa",
          "Limay",
          "Mariveles",
          "Morong",
          "Orani",
          "Orion",
          "Pilar",
          "Samal",
        ],
      },
      {
        provinceName: "Bulacan",
        cities: [
          "Angat",
          "Balagtas",
          "Baliwag",
          "Bocaue",
          "Bulakan",
          "Bustos",
          "Calumpit",
          "Doña Remedios Trinidad",
          "Guiguinto",
          "Hagonoy",
          "Malolos",
          "Marilao",
          "Meycauayan",
          "Norzagaray",
          "Obando",
          "Pandi",
          "Paombong",
          "Plaridel",
          "Pulilan",
          "San Ildefonso",
          "San Jose del Monte",
          "San Miguel",
          "San Rafael",
          "Santa Maria",
        ],
      },
      {
        provinceName: "Nueva Ecija",
        cities: [
          "Aliaga",
          "Bongabon",
          "Cabanatuan",
          "Cabiao",
          "Carranglan",
          "Cuyapo",
          "Gabaldon (Bitulok & Sabani)",
          "Gapan",
          "General Mamerto Natividad",
          "General Tinio (Papaya)",
          "Guimba",
          "Jaen",
          "Laur",
          "Licab",
          "Llanera",
          "Lupao",
          "Science City of Muñoz",
          "Nampicuan",
          "Palayan",
          "Pantabangan",
          "Peñaranda",
          "Quezon",
          "Rizal",
          "San Antonio",
          "San Isidro",
          "San Jose (Cabaritan)",
          "San Leonardo",
          "Santa Rosa",
          "Santo Domingo",
          "Talavera",
          "Talugtug",
          "Zaragoza",
        ],
      },
      {
        provinceName: "Pampanga",
        cities: [
          "Apalit",
          "Arayat, Pampanga",
          "Bacolor",
          "Candaba",
          "Floridablanca, Pampanga",
          "Guagua",
          "Lubao",
          "Macabebe",
          "Magalang",
          "Masantol",
          "Mexico, Pampanga",
          "Minalin",
          "Porac",
          "San Luis, Pampanga",
          "San Simon, Pampanga",
          "Santa Ana, Pampanga",
          "Santa Rita, Pampanga",
          "Santo Tomas, Pampanga",
          "Sasmuan",
        ],
      },
      {
        provinceName: "Tarlac",
        cities: [
          "Anao",
          "Bamban",
          "Camiling",
          "Capas",
          "Concepcion",
          "Gerona",
          "La Paz",
          "Mayantoc",
          "Moncada",
          "Paniqui",
          "Pura",
          "Ramos",
          "San Clemente",
          "San Jose",
          "San Manuel",
          "Santa Ignacia",
          "Tarlac City",
          "Victoria",
        ],
      },
      {
        provinceName: "Zambales",
        cities: [
          "Botolan",
          "Cabangan",
          "Candelaria",
          "Castillejos",
          "Iba",
          "Masinloc",
          "Olongapo",
          "Palauig",
          "San Antonio",
          "San Felipe",
          "San Marcelino",
          "San Narciso",
          "Santa Cruz",
          "Subic",
        ],
      },
    ],
  },
  {
    region: "REGION IV-A (CALABARZON)",
    provinces: [
      {
        provinceName: "Batangas",
        cities: [
          "Agoncillo",
          "Alitagtag",
          "Balayan",
          "Balete",
          "Batangas City",
          "Bauan",
          "Calaca",
          "Calatagan",
          "Cuenca",
          "Ibaan",
          "Laurel",
          "Lemery",
          "Lian",
          "Lipa",
          "Lobo",
          "Mabini",
          "Malvar",
          "Mataasnakahoy",
          "Nasugbu",
          "Padre Garcia",
          "Rosario",
          "San Jose",
          "San Juan",
          "San Luis",
          "San Nicolas",
          "San Pascual",
          "Santa Teresita",
          "Santo Tomas",
          "Taal",
          "Talisay",
          "Tanauan",
          "Taysan",
          "Tingloy",
          "Tuy",
        ],
      },
      {
        provinceName: "Cavite",
        cities: [
          "Alfonso",
          "Amadeo",
          "Bacoor",
          "Carmona",
          "Cavite City",
          "Dasmariñas",
          "General Emilio Aguinaldo",
          "General Mariano Alvarez",
          "General Trias",
          "Imus",
          "Indang",
          "Kawit",
          "Magallanes",
          "Maragondon",
          "Mendez",
          "Naic",
          "Noveleta",
          "Rosario",
          "Silang",
          "Tagaytay",
          "Tanza",
          "Ternate",
          "Trece Martires City",
        ],
      },
      {
        provinceName: "Laguna",
        cities: [
          "Alaminos, Laguna",
          "Bay, Laguna",
          "Calauan",
          "Cavinti",
          "Famy",
          "Kalayaan, Laguna",
          "Liliw",
          "Los Baños, Laguna",
          "Luisiana",
          "Lumban",
          "Mabitac",
          "Magdalena, Laguna",
          "Majayjay",
          "Nagcarlan",
          "Paete",
          "Pagsanjan",
          "Pakil",
          "Pangil",
          "Pila, Laguna",
          "Rizal, Laguna",
          "Santa Cruz, Laguna",
          "Santa Maria, Laguna",
          "Siniloan",
          "Victoria, Laguna",
        ],
      },
      {
        provinceName: "Quezon",
        cities: [
          "Agdangan",
          "Alabat",
          "Atimonan",
          "Buenavista",
          "Burdeos",
          "Calauag",
          "Candelaria",
          "Catanauan",
          "Dolores",
          "General Luna",
          "General Nakar",
          "Guinayangan",
          "Gumaca",
          "Infanta",
          "Jomalig",
          "Lopez",
          "Lucban",
          "Lucena",
          "Macalelon",
          "Mauban",
          "Mulanay",
          "Padre Burgos",
          "Pagbilao",
          "Panukulan",
          "Patnanungan",
          "Perez",
          "Pitogo",
          "Plaridel",
          "Polillo",
          "Quezon",
          "Real",
          "Sampaloc",
          "San Andres",
          "San Antonio",
          "San Francisco",
          "San Narciso",
          "Sariaya",
          "Tagkawayan",
          "Tayabas",
          "Tiaong",
          "Unisan",
        ],
      },
      {
        provinceName: "Rizal",
        cities: [
          "Angono",
          "Antipolo",
          "Baras",
          "Binangonan",
          "Cainta",
          "Cardona",
          "Jalajala",
          "Morong",
          "Pililla",
          "Rodriguez",
          "San Mateo",
          "Tanay",
          "Taytay",
          "Teresa",
        ],
      },
    ],
  },
  {
    region: "REGION IV-B (MIMAROPA)",
    provinces: [
      {
        provinceName: "Marinduque",
        cities: [
          "Boac",
          "Buenavista",
          "Gasan",
          "Mogpog",
          "Santa Cruz",
          "Torrijos",
        ],
      },
      {
        provinceName: "Occidental Mindoro",
        cities: [
          "Abra de Ilog",
          "Calintaan",
          "Looc, Occidental Mindoro",
          "Lubang, Occidental Mindoro",
          "Magsaysay, Occidental Mindoro",
          "Mamburao",
          "Paluan",
          "Rizal, Occidental Mindoro",
          "Sablayan",
          "San Jose, Occidental Mindoro",
          "Santa Cruz, Occidental Mindoro",
        ],
      },
      {
        provinceName: "Oriental Mindoro",
        cities: [
          "Baco, Oriental Mindoro",
          "Bansud",
          "Bongabong",
          "Bulalacao",
          "Gloria, Oriental Mindoro",
          "Mansalay",
          "Naujan",
          "Pinamalayan",
          "Pola, Oriental Mindoro",
          "Puerto Galera",
          "Roxas, Oriental Mindoro",
          "San Teodoro, Oriental Mindoro",
          "Socorro, Oriental Mindoro",
          "Victoria, Oriental Mindoro",
        ],
      },
      {
        provinceName: "Palawan",
        cities: [
          "Aborlan",
          "Agutaya",
          "Araceli",
          "Balabac",
          "Bataraza",
          "Brooke's Point",
          "Busuanga",
          "Cagayancillo",
          "Coron",
          "Culion",
          "Cuyo",
          "Dumaran",
          "El Nido",
          "Kalayaan",
          "Linapacan",
          "Magsaysay",
          "Narra",
          "Puerto Princesa",
          "Quezon",
          "Rizal",
          "Roxas",
          "San Vicente",
          "Sofronio Española",
          "Taytay",
        ],
      },
      {
        provinceName: "Romblon",
        cities: [
          "Alcantara",
          "Banton (Jones)",
          "Cajidiocan",
          "Calatrava",
          "Concepcion",
          "Corcuera",
          "Ferrol",
          "Looc",
          "Magdiwang",
          "Odiongan",
          "Romblon",
          "San Agustin",
          "San Andres",
          "San Fernando",
          "San Jose",
          "Santa Fe",
          "Santa Maria",
        ],
      },
    ],
  },
  {
    region: "REGION IX (ZAMBOANGA PENINSULA)",
    provinces: [
      {
        provinceName: "Zamboanga Del Norte",
        cities: [
          "Baliguian",
          "Godod",
          "Gutalac",
          "Jose Dalman",
          "Kalawit",
          "Katipunan",
          "La Libertad",
          "Labason",
          "Leon B. Postigo",
          "Liloy",
          "Manukan",
          "Mutia",
          "Piñan",
          "Polanco",
          "Rizal",
          "Roxas",
          "Salug",
          "Sergio Osmeña",
          "Siayan",
          "Sibuco",
          "Sibutad",
          "Sindangan",
          "Siocon",
          "Sirawai",
          "Tampilisan",
        ],
      },
      {
        provinceName: "Zamboanga Del Sur",
        cities: [
          "Aurora",
          "Bayog",
          "Dimataling",
          "Dinas",
          "Dumalinao",
          "Dumingag",
          "Guipos",
          "Josefina",
          "Kumalarang",
          "Labangan",
          "Lakewood",
          "Lapuyan",
          "Mahayag",
          "Margosatubig",
          "Midsalip",
          "Molave",
          "Pagadian",
          "Pitogo",
          "Ramon Magsaysay",
          "San Miguel",
          "San Pablo",
          "Sominot",
          "Tabina",
          "Tambulig",
          "Tigbao",
          "Tukuran",
          "Vincenzo A. Sagun",
          "Zamboanga City",
        ],
      },
      {
        provinceName: "Zamboanga Sibugay",
        cities: [
          "Alicia",
          "Buug",
          "Diplahan",
          "Imelda",
          "Ipil",
          "Kabasalan",
          "Mabuhay",
          "Malangas",
          "Naga",
          "Olutanga",
          "Payao",
          "Roseller Lim",
          "Siay",
          "Talusan",
          "Titay",
          "Tungawan",
        ],
      },
    ],
  },
  {
    region: "REGION V (BICOL REGION)",
    provinces: [
      {
        provinceName: "Albay",
        cities: [
          "Bacacay",
          "Camalig",
          "Daraga",
          "Guinobatan",
          "Jovellar",
          "Legazpi",
          "Libon",
          "Ligao",
          "Malilipot",
          "Malinao",
          "Manito",
          "Oas",
          "Pio Duran",
          "Polangui",
          "Rapu-Rapu",
          "Santo Domingo",
          "Tabaco",
          "Tiwi",
        ],
      },
      {
        provinceName: "Camarines Norte",
        cities: [
          "Basud",
          "Capalonga",
          "Daet",
          "Jose Panganiban",
          "Labo",
          "Mercedes",
          "Paracale",
          "San Lorenzo Ruiz",
          "San Vicente",
          "Santa Elena",
          "Talisay",
          "Vinzons",
        ],
      },
      {
        provinceName: "Camarines Sur",
        cities: [
          "Baao",
          "Balatan",
          "Bato",
          "Bombon",
          "Buhi",
          "Bula",
          "Cabusao",
          "Calabanga",
          "Camaligan",
          "Canaman",
          "Caramoan",
          "Del Gallego",
          "Gainza",
          "Garchitorena",
          "Goa",
          "Iriga",
          "Lagonoy",
          "Libmanan",
          "Lupi",
          "Magarao",
          "Milaor",
          "Minalabac",
          "Nabua",
          "Naga",
          "Ocampo",
          "Pamplona",
          "Pasacao",
          "Pili",
          "Presentacion",
          "Ragay",
          "Sagñay",
          "San Fernando",
          "San Jose",
          "Sipocot",
          "Siruma",
          "Tigaon",
          "Tinambac",
        ],
      },
      {
        provinceName: "Catanduanes",
        cities: [
          "Bagamanoc",
          "Baras",
          "Bato",
          "Caramoran",
          "Gigmoto",
          "Pandan",
          "Panganiban",
          "San Andres",
          "San Miguel",
          "Viga",
          "Virac",
        ],
      },
      {
        provinceName: "Masbate",
        cities: [
          "Aroroy",
          "Baleno",
          "Balud",
          "Batuan",
          "Cataingan",
          "Cawayan",
          "Claveria",
          "Dimasalang",
          "Esperanza",
          "Mandaon",
          "Masbate City",
          "Milagros",
          "Mobo",
          "Monreal",
          "Palanas",
          "Pio V. Corpus",
          "Placer",
          "San Fernando",
          "San Jacinto",
          "San Pascual",
          "Uson",
        ],
      },
      {
        provinceName: "Sorsogon",
        cities: [
          "Barcelona",
          "Bulan",
          "Bulusan",
          "Casiguran",
          "Castilla",
          "Donsol",
          "Gubat",
          "Irosin",
          "Juban",
          "Magallanes",
          "Matnog",
          "Pilar",
          "Prieto Diaz",
          "Santa Magdalena",
          "Sorsogon City",
        ],
      },
    ],
  },
  {
    region: "REGION VI (WESTERN VISAYAS)",
    provinces: [
      {
        provinceName: "Aklan",
        cities: [
          "Altavas",
          "Balete",
          "Banga",
          "Batan",
          "Buruanga",
          "Ibajay",
          "Kalibo",
          "Lezo",
          "Libacao",
          "Madalag",
          "Makato",
          "Malay",
          "Malinao",
          "Nabas",
          "New Washington",
          "Numancia",
          "Tangalan",
        ],
      },
      {
        provinceName: "Antique",
        cities: [
          "Anini-y",
          "Barbaza (Nalupa)",
          "Belison",
          "Bugasong (Bugason)",
          "Caluya",
          "Culasi (Bacong)",
          "Hamtic",
          "Laua-an",
          "Libertad (Inayawan)",
          "Pandan",
          "Patnongon",
          "San Jose de Buenavista",
          "San Remigio (Tigbagacay)",
          "Sebaste (Ipayo)",
          "Sibalom",
          "Tibiao",
          "Tobias Fornier (Dao)",
          "Valderrama (Kaberi-an)",
        ],
      },
      {
        provinceName: "Capiz",
        cities: [
          "Cuartero",
          "Dao",
          "Dumalag",
          "Dumarao",
          "Ivisan",
          "Jamindan",
          "Maayon",
          "Mambusao",
          "Panay",
          "Panitan",
          "Pilar",
          "Pontevedra",
          "President Roxas",
          "Roxas City",
          "Sapian",
          "Sigma",
          "Tapaz",
        ],
      },
      {
        provinceName: "Guimaras",
        cities: [
          "Buenavista",
          "Jordan",
          "Nueva Valencia",
          "San Lorenzo",
          "Sibunag",
        ],
      },
      {
        provinceName: "IloIlo",
        cities: [
          "Ajuy, Iloilo",
          "Alimodian",
          "Anilao, Iloilo",
          "Badiangan",
          "Balasan",
          "Banate, Iloilo",
          "Barotac Nuevo",
          "Barotac Viejo",
          "Batad, Iloilo",
          "Bingawan",
          "Cabatuan, Iloilo",
          "Calinog",
          "Carles, Iloilo",
          "Concepcion, Iloilo",
          "Dingle, Iloilo",
          "Dueñas, Iloilo",
          "Dumangas",
          "Estancia, Iloilo",
          "Guimbal",
          "Igbaras",
          "Janiuay",
          "Lambunao",
          "Leganes, Iloilo",
          "Lemery, Iloilo",
          "Leon, Iloilo",
          "Maasin, Iloilo",
          "Miagao",
          "Mina, Iloilo",
          "New Lucena",
          "Oton",
          "Pavia, Iloilo",
          "Pototan",
          "San Dionisio, Iloilo",
          "San Enrique, Iloilo",
          "San Joaquin, Iloilo",
          "San Miguel, Iloilo",
          "San Rafael, Iloilo",
          "Santa Barbara, Iloilo",
          "Sara, Iloilo",
          "Tigbauan",
          "Tubungan",
          "Zarraga",
        ],
      },
      {
        provinceName: "Negros Occidental",
        cities: [
          "Bacolod City",
          "Bago City",
          "Binalbagan",
          "Cadiz City",
          "Calatrava",
          "Candoni",
          "Cauayan",
          "Don Salvador Benedicto",
          "Enrique B. Magalona",
          "Escalante City",
          "Himamaylan City",
          "Hinigaran",
          "Hinoba-an",
          "Ilog",
          "Isabela",
          "Kabankalan City",
          "La Carlota City",
          "La Castellana",
          "Manapla",
          "Moises Padilla",
          "Murcia",
          "Pontevedra",
          "Pulupandan",
          "Sagay City",
          "San Carlos City",
          "San Enrique",
          "Silay City",
          "Sipalay City",
          "Talisay City",
          "Toboso",
          "Valladolid",
          "Victorias City",
        ],
      },
    ],
  },
  {
    region: "REGION VII (CENTRAL VISAYAS)",
    provinces: [
      {
        provinceName: "Bohol",
        cities: [
          "Alburquerque",
          "Antequera",
          "Baclayon",
          "Balilihan",
          "Calape",
          "Catigbian",
          "Corella",
          "Cortes",
          "Dauis",
          "Loon",
          "Maribojoc",
          "Panglao",
          "Sikatuna",
          "Tagbilaran",
          "Tubigon",
          "Bien Unido",
          "Buenavista",
          "Clarin",
          "Dagohoy",
          "Danao",
          "Getafe",
          "Inabanga",
          "President Carlos P. Garcia",
          "Sagbayan",
          "San Isidro",
          "San Miguel",
          "Talibon",
          "Trinidad",
          "Ubay",
          "Alicia",
          "Anda",
          "Batuan",
          "Bilar",
          "Candijay",
          "Carmen",
          "Dimiao",
          "Duero",
          "Garcia Hernandez",
          "Guindulman",
          "Jagna",
          "Sevilla",
          "Lila",
          "Loay",
          "Loboc",
          "Mabini",
          "Pilar",
          "Sierra Bullones",
          "Valencia",
        ],
      },
      {
        provinceName: "Cebu",
        cities: [
          "Alcantara",
          "Alcoy",
          "Alegria",
          "Aloguinsan",
          "Argao",
          "Asturias",
          "Badian",
          "Balamban",
          "Bantayan",
          "Barili",
          "Bogo",
          "Boljoon",
          "Borbon",
          "Carcar",
          "Carmen",
          "Catmon",
          "Cebu City",
          "Compostela",
          "Consolacion",
          "Cordova",
          "Daanbantayan",
          "Dalaguete",
          "Danao",
          "Dumanjug",
          "Ginatilan",
          "Lapu-Lapu City",
          "Liloan",
          "Madridejos",
          "Malabuyoc",
          "Mandaue",
          "Medellin",
          "Minglanilla",
          "Moalboal",
          "Naga City",
          "Oslob",
          "Pilar",
          "Pinamungajan",
          "Poro",
          "Ronda",
          "Samboan",
          "San Fernando",
          "San Francisco",
          "San Remigio",
          "Santa Fe",
          "Santander",
          "Sibonga",
          "Sogod",
          "Tabogon",
          "Tabuelan",
          "Talisay",
          "Toledo City",
          "Tuburan",
          "Tudela",
        ],
      },
      {
        provinceName: "Negros Oriental",
        cities: [
          "Amlan (Ayuquitan)",
          "Ayungon",
          "Bacong",
          "Bais",
          "Basay",
          "Bayawan (Tolong)",
          "Bindoy (Payabon)",
          "Canlaon",
          "Dauin",
          "Dumaguete",
          "Guihulngan",
          "Jimalalud",
          "La Libertad",
          "Mabinay",
          "Manjuyod",
          "Pamplona",
          "San Jose",
          "Santa Catalina",
          "Siaton",
          "Sibulan",
          "Tanjay",
          "Tayasan",
          "Valencia (Luzurriaga)",
          "Vallehermoso",
          "Zamboanguita",
        ],
      },
      {
        provinceName: "Siquijor",
        cities: [
          "Enrique Villanueva",
          "Larena",
          "Lazi",
          "Maria",
          "San Juan",
          "Siquijor",
        ],
      },
    ],
  },
  {
    region: "REGION VIII (EASTERN VISAYAS)",
    provinces: [
      {
        provinceName: "Biliran",
        cities: [
          "Almeria",
          "Biliran",
          "Cabucgayan",
          "Caibiran",
          "Culaba",
          "Kawayan",
          "Maripipi",
          "Naval",
        ],
      },
      {
        provinceName: "Eastern Samar",
        cities: [
          "Arteche",
          "Balangiga",
          "Balangkayan",
          "Borongan",
          "Can-avid",
          "Dolores",
          "General MacArthur",
          "Giporlos",
          "Guiuan",
          "Hernani",
          "Jipapad",
          "Lawaan",
          "Llorente",
          "Maslog",
          "Maydolong",
          "Mercedes",
          "Oras",
          "Quinapondan",
          "Salcedo",
          "San Julian",
          "San Policarpo",
          "Sulat",
          "Taft",
        ],
      },
      {
        provinceName: "Leyte",
        cities: [
          "Abuyog",
          "Alangalang",
          "Albuera",
          "Babatngon",
          "Barugo",
          "Bato",
          "Baybay",
          "Burauen",
          "Calubian",
          "Capoocan",
          "Carigara",
          "Dagami",
          "Dulag",
          "Hilongos",
          "Hindang",
          "Inopacan",
          "Isabel",
          "Jaro",
          "Javier (Bugho)",
          "Julita",
          "Kananga",
          "La Paz",
          "Leyte",
          "MacArthur",
          "Mahaplag",
          "Matag-ob",
          "Mayorga",
          "Merida",
          "Ormoc",
          "Palo",
          "Palompon",
          "Pastrana",
          "San Isidro",
          "San Miguel",
          "Santa Fe",
          "Tabango",
          "Tabontabon",
          "Tacloban",
          "Tanauan",
          "Tolosa",
          "Tunga",
          "Villaba",
        ],
      },
      {
        provinceName: "Northern Samar",
        cities: [
          "Allen",
          "Biri",
          "Bobon",
          "Capul",
          "Catarman",
          "Catubig",
          "Gamay",
          "Laoang",
          "Lapinig",
          "Las Navas",
          "Lavezares",
          "Lope de Vega",
          "Mapanas",
          "Mondragon",
          "Palapag",
          "Pambujan",
          "Rosario",
          "San Antonio",
          "San Isidro",
          "San Jose",
          "San Roque",
          "San Vicente",
          "Silvino Lobos",
          "Victoria",
        ],
      },
      {
        provinceName: "Western Samar",
        cities: [
          "Almagro",
          "Basey",
          "Calbayog",
          "Calbiga",
          "Catbalogan",
          "Daram",
          "Gandara",
          "Hinabangan",
          "Jiabong",
          "Marabut",
          "Matuguinao",
          "Motiong",
          "Pagsanghan",
          "Paranas (Wright)",
          "Pinabacdao",
          "San Jorge",
          "San Jose de Buan",
          "San Sebastian",
          "Santa Margarita",
          "Santa Rita",
          "Santo Niño",
          "Tagapul-an",
          "Talalora",
          "Tarangnan",
          "Villareal",
          "Zumarraga",
        ],
      },
      {
        provinceName: "Southern Leyte",
        cities: [
          "Anahawan",
          "Bontoc, Southern Leyte",
          "Hinunangan",
          "Hinundayan",
          "Libagon",
          "Liloan, Southern Leyte",
          "Limasawa",
          "Macrohon",
          "Malitbog, Southern Leyte",
          "Padre Burgos, Southern Leyte",
          "Pintuyan",
          "Saint Bernard, Southern Leyte",
          "San Francisco, Southern Leyte",
          "San Juan, Southern Leyte",
          "San Ricardo",
          "Silago",
          "Sogod, Southern Leyte",
          "Tomas Oppus",
        ],
      },
    ],
  },
  {
    region: "REGION X (NORTHERN MINDANAO)",
    provinces: [
      {
        provinceName: "Bukidnon",
        cities: [
          "Baungon",
          "Cabanglasan",
          "Damulog",
          "Dangcagan",
          "Don Carlos",
          "Impasugong",
          "Kadingilan",
          "Kalilangan",
          "Kibawe",
          "Kitaotao",
          "Lantapan",
          "Libona",
          "Malaybalay",
          "Malitbog",
          "Manolo Fortich",
          "Maramag",
          "Pangantucan",
          "Quezon",
          "San Fernando",
          "Sumilao",
          "Talakag",
          "Valencia",
        ],
      },
      {
        provinceName: "Camiguin",
        cities: ["Catarman", "Guinsiliban", "Mahinog", "Mambajao", "Sagay"],
      },
      {
        provinceName: "Lanao Del Norte",
        cities: [
          "Bacolod",
          "Baloi",
          "Baroy",
          "Iligan",
          "Kapatagan",
          "Kauswagan",
          "Kolambugan",
          "Lala",
          "Linamon",
          "Magsaysay",
          "Maigo",
          "Matungao",
          "Munai",
          "Nunungan",
          "Pantao Ragat",
          "Pantar",
          "Poona Piagapo",
          "Salvador",
          "Sapad",
          "Sultan Naga Dimaporo (Karomatan)",
          "Tagoloan",
          "Tangcal",
          "Tubod",
        ],
      },
      {
        provinceName: "Misamis Occidental",
        cities: [
          "Aloran",
          "Baliangao",
          "Bonifacio",
          "Calamba",
          "Clarin",
          "Concepcion",
          "Don Victoriano Chiongbian (Don Mariano Marcos)",
          "Jimenez",
          "Lopez Jaena",
          "Oroquieta",
          "Ozamiz",
          "Panaon",
          "Plaridel",
          "Sapang Dalaga",
          "Sinacaban",
          "Tangub",
          "Tudela",
        ],
      },
      {
        provinceName: "Misamis Oriental",
        cities: [
          "Alubijid",
          "Balingasag",
          "Balingoan",
          "Binuangan",
          "Cagayan de Oro",
          "Claveria",
          "El Salvador",
          "Gingoog",
          "Gitagum",
          "Initao",
          "Jasaan",
          "Kinoguitan",
          "Lagonglong",
          "Laguindingan",
          "Libertad",
          "Lugait",
          "Magsaysay",
          "Manticao",
          "Medina",
          "Naawan",
          "Opol",
          "Salay",
          "Sugbongcogon",
          "Tagoloan",
          "Talisayan",
          "Villanueva",
        ],
      },
    ],
  },
  {
    region: "REGION XI (DAVAO REGION)",
    provinces: [
      {
        provinceName: "Compostella Valley",
        cities: [
          "Compostela",
          "Laak",
          "Mabini",
          "Maco",
          "Maragusan",
          "Mawab",
          "Monkayo",
          "Montevista",
          "Nabunturan",
          "New Bataan",
          "Pantukan",
        ],
      },
      {
        provinceName: "Davao Del Norte",
        cities: [
          "Asuncion",
          "Braulio E. Dujali",
          "Carmen",
          "Kapalong",
          "New Corella",
          "Panabo",
          "Samal",
          "San Isidro",
          "Santo Tomas",
          "Tagum",
          "Talaingod",
        ],
      },
      {
        provinceName: "Davao Del Sur",
        cities: [
          "Bansalan",
          "Davao City",
          "Digos",
          "Hagonoy",
          "Kiblawan",
          "Magsaysay",
          "Malalag",
          "Matanao",
          "Padada",
          "Santa Cruz",
          "Sulop",
        ],
      },
      {
        provinceName: "Davao Occidental",
        cities: [
          "Don Marcelino",
          "Jose Abad Santos",
          "Malita",
          "Santa Maria",
          "Sarangani",
        ],
      },
      {
        provinceName: "Davao Oriental",
        cities: [
          "Baganga",
          "Banaybanay",
          "Boston",
          "Caraga",
          "Cateel",
          "Governor Generoso",
          "Lupon",
          "Manay",
          "Mati",
          "San Isidro",
          "Tarragona",
        ],
      },
    ],
  },
  {
    region: "REGION XII (SOCCSKARGEN)",
    provinces: [
      {
        provinceName: "Cotabato (NORTH COTABATO)",
        cities: [
          "Alamada",
          "Aleosan",
          "Antipas",
          "Arakan",
          "Banisilan",
          "Carmen",
          "Kabacan",
          "Kidapawan City",
          "Libungan",
          "M'lang",
          "Magpet",
          "Makilala",
          "Matalam",
          "Midsayap",
          "Pigcawayan",
          "Pikit",
          "President Roxas",
          "Tulunan",
        ],
      },
      {
        provinceName: "Sarangani",
        cities: [
          "Alabel",
          "Glan",
          "Kiamba",
          "Maasim",
          "Maitum",
          "Malapatan",
          "Malungon",
        ],
      },
      {
        provinceName: "South Cotabato",
        cities: [
          "Banga",
          "General Santos",
          "Koronadal",
          "Lake Sebu",
          "Norala",
          "Polomolok",
          "Santo Niño",
          "Surallah",
          "T'Boli",
          "Tampakan",
          "Tantangan",
          "Tupi",
        ],
      },
      {
        provinceName: "Sultan Kudarat",
        cities: [
          "Bagumbayan",
          "Columbio",
          "Esperanza",
          "Isulan",
          "Kalamansig",
          "Lambayong",
          "Lebak",
          "Lutayan",
          "Palimbang",
          "President Quirino",
          "Senator Ninoy Aquino",
        ],
      },
    ],
  },
  {
    region: "REGION XIII (CARAGA)",
    provinces: [
      {
        provinceName: "Agusan del Norte",
        cities: [
          "Buenavista",
          "Carmen",
          "Jabonga",
          "Kitcharao",
          "Las Nieves",
          "Magallanes",
          "Nasipit",
          "Remedios T. Romualdez",
          "Santiago",
          "Tubay",
        ],
      },
      {
        provinceName: "Agusan del Sur",
        cities: [
          "Bayugan",
          "Bunawan",
          "Esperanza",
          "La Paz",
          "Loreto",
          "Prosperidad",
          "Rosario",
          "San Francisco",
          "San Luis",
          "Santa Josefa",
          "Sibagat",
          "Talacogon",
          "Trento",
          "Veruela",
        ],
      },
      {
        provinceName: "Dinagat Islands",
        cities: [
          "Basilisa",
          "Cagdianao",
          "Dinagat",
          "Libjo",
          "Loreto",
          "San Jose",
          "Tubajon",
        ],
      },
      {
        provinceName: "Surigao del Norte",
        cities: [
          "Alegria",
          "Bacuag",
          "Burgos",
          "Claver",
          "Dapa",
          "Del Carmen",
          "General Luna",
          "Gigaquit",
          "Mainit",
          "Malimono",
          "Pilar",
          "Placer",
          "San Benito",
          "San Francisco (Anao-Aon)",
          "San Isidro",
          "Santa Monica (Sapao)",
          "Sison",
          "Socorro",
          "Surigao City",
          "Tagana-an",
          "Tubod",
        ],
      },
      {
        provinceName: "Surigao del Sur",
        cities: [
          "Barobo",
          "Bayabas",
          "Bislig",
          "Cagwait",
          "Cantilan",
          "Carmen",
          "Carrascal",
          "Cortes",
          "Hinatuan",
          "Lanuza",
          "Lianga",
          "Lingig",
          "Madrid",
          "Marihatag",
          "San Agustin",
          "San Miguel",
          "Tagbina",
          "Tago",
          "Tandag",
        ],
      },
    ],
  },
];

export default regionsWithProvinces;
